### ISSUE TITLE
Please support Enterprise Linux 7 (EL7) again

### ISSUE THREAD

**Issue by flybyray** [robertdebock/ansible-role-python_pip#10]
## Proposed feature

python_pip should support EL7 again

## Rationale

I am not quite happy how this was removed here and from my perspective this is more a bug then a feature: https://github.com/robertdebock/ansible-role-python_pip/commit/4962eb1f587abb295613ada5137919fddecd22a3#commitcomment-63877727

## Additional context

> ["The interpreter used by Ansible (see ansible_python_interpreter) requires the setuptools package, regardless of the version of pip set with the executable option."](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html#notes)

## Optional Bug Description

If this would be a bug. 

Error:

```txt
TASK [robertdebock.development_environment.python_pip : update pip] **********************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named pkg_resources
fatal: [localhost]: FAILED! => changed=false 
  msg: Failed to import the required Python library (setuptools) on localhost's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```

To fix this please ensure requirements first "setuptools package".

**Comment by flybyray** [comment]
https://github.com/pypa/pip/issues/6148 - the relevant drop support information.

something like this could help:

```yaml
- name: update pip
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest  # noqa package-latest
    executable: "{{ python_pip_executable | default(omit) }}"
  loop:
    - "pip{{ '<21' if ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7' }}"
    - setuptools
  when:
    - python_pip_update | bool
```

in please of this:
https://github.com/robertdebock/ansible-role-python_pip/blob/master/tasks/main.yml#L34-L42

**Comment by robertdebock** [comment]
Fixed with the latest release. Thanks for your feedback!
