### ISSUE TITLE
I need /etc/pip.conf to point to my pypi proxy

### ISSUE THREAD

**Issue by bbaassssiiee** [robertdebock/ansible-role-python_pip#4]
**Is your feature request related to a problem? Please describe.**
We have our pypi proxy, but not a proxy. In air-gapped environments I would like to get at pypi libraries published by the organization.

**Describe the solution you'd like**
I'd like to use a template for /etc/pip.conf

**Describe alternatives you've considered**
File in each homedir is maintenance burden.

**Additional context**
```
# /etc/pip.conf
[global]
## Proxy config for Python libraries. Example:
## index-url = https://user:password@proxy:8443/artifactory/pypi/pypi-virtual/simple
{% if artifactory_hostname is defined%}
index-url = https://{{ artifactory_hostname }}:{{ artifactory_port  }}/{{ artifactory_repo_path }}
# cert = {{certificate_path }}
{% endif %}
```

**Comment by robertdebock** [comment]
Cool, I'll work on it.

Thanks @bbaassssiiee for your feedback.
